CREATE DATABASE  IF NOT EXISTS `deadpoets` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `deadpoets`;
-- MySQL dump 10.13  Distrib 5.6.17, for Win32 (x86)
--
-- Host: localhost    Database: deadpoets
-- ------------------------------------------------------
-- Server version	5.6.19

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `post`
--

DROP TABLE IF EXISTS `post`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `post` (
  `post_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `writer_id` bigint(20) DEFAULT NULL,
  `text` text NOT NULL,
  `curdate` datetime NOT NULL,
  `showPost` tinyint(4) NOT NULL,
  `title` text,
  PRIMARY KEY (`post_id`),
  KEY `writer_id` (`writer_id`),
  CONSTRAINT `post_id` FOREIGN KEY (`writer_id`) REFERENCES `writer` (`writer_id`)
) ENGINE=InnoDB AUTO_INCREMENT=58 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `post`
--

LOCK TABLES `post` WRITE;
/*!40000 ALTER TABLE `post` DISABLE KEYS */;
INSERT INTO `post` VALUES (47,33,'The science-fiction writer Robert A. Heinlein once described himself as âa preacher with no church.â More accurately, he was a preacher with too many churches. Rare among the many intellectual gurus whose fame mushroomed in the 1960s, Heinlein was a beacon for hippies and hawks, libertarians and authoritarians, and many other contending faithsâbut rarely at the same time. While America became increasingly liberal, he became increasingly right wing, and it hobbled his once-formidable imagination. His career, as a new biography inadvertently proves, is a case study in the literary perils of political extremism.','2014-11-18 01:51:21',1,'Robert A. Heinlein became increasingly right wing, and his novels suffered for it '),(48,34,'Robert Heinlein was a solipsist and an extrapolationist. These two components of his personalityâhis tendency to see reality as an extension of himself, and his compulsion to push ideas to their logical conclusionâwere evident in his personality at a very young age. In later life, sometimes these tendencies would war with each other and sometimes they fused together, but they seem to have been present from early on.\r\n\r\nBorn in Butler, Missouri in 1907, the third of seven children, Heinlein grew up mostly in Kansas in a household kept barely solvent by his fatherâs salary. The solipsism set in at an early age. As Heinlein wrote in 1955 to a friend, âI have had a dirty suspicion since I was about six that all consciousness is one and that all the actors I see around me â¦ are myself, at different points in the recordâs grooves.â  Heinleinâs high school year book offered this prescient tagline: âHe thinks in terms of the fifth dimension, never stopping at the fourth.â','2014-11-18 01:55:16',1,'More about Heinlein'),(51,33,'Roger Zelazny made his name with a group of novellas which demonstrated just how intense an emotional charge could be generated by the stock imagery of sf; the most famous of these is \'A Rose for Ecclesiastes\' in which a poet struggles to convince dying and sterile Martians that life is worth continuing. Zelazny continued to write excellent short stories throughout his career. Most of his novels deal, one way or another, with tricksters and mythology, often with rogues who become gods, like Sam in Lord of Light, who reinvents Buddhism as a vehicle for political subversion against his fellow-crew members who, using transhumanist technology, have appointed themselves gods on a colony planet, where the social system is derived from classical H ...more','2014-11-18 05:32:22',1,'\r\nAbout this author - Roger Zelazny'),(52,33,'He was a poet, first, last, always. His words sang.\r\n\r\nHe was a storyteller without peer. He created worlds as colorful and exotic and memorable as any our genre has ever seen.\r\n\r\nBut most of all, I will remember his people. Corwin of Amber and his troublesome siblings. Charles Render, the dream master. The Sleeper, Croyd Crenson, who never learned algebra. Fred Cassidy climbing on his rooftops. Conrad. Dilvish the Damned. Francis Sandow. Billy Blackhorse Singer. Jarry Dark. The Jack of Shadows. Hell Tanner. Snuff.\r\n\r\nAnd Sam. Him especially. âHis followers called him Mahasamatman and said he was a god. He preferred to drop the Maha- and the atman, however, and called himself Sam. He never claimed to be a god. But then, he never claimed not to be a god.â','2014-11-18 05:33:23',1,'In Memoriam: Roger Zelazny'),(53,33,'Samuel Ray Delany, also known as \"Chip,\" is an award-winning American science fiction author. He was born to a prominent black family on April 1, 1942, and raised in Harlem. His mother, Margaret Carey Boyd Delany, was a library clerk in the New York Public Library system. His father, Samuel Ray Delany, Senior, ran a successful Harlem undertaking establishment, Levy & Delany Funeral Home, on 7th Avenue, between 1938 and his death in 1960. The family lived in the top two floors of the three-story private house between five- and six-story Harlem apartment buildings. Delany\'s aunts were Sadie and Bessie Delany; Delany used some of their adventures as the basis for the adventures of his characters Elsie and Corry in the opening novella Atlan ...more','2014-11-18 05:38:04',1,'\r\nAbout this author Samuel R. Delany\r\n\r\n'),(54,33,'Recurring themes in Delany\'s work include mythology, memory, language, sexuality, and perception. Class, position in society, and the ability to move from one social stratum to another are motifs that were touched on in his earlier work and became more significant in his later fiction and non-fiction, both. Many of Delany\'s later (mid-1980s and beyond) works have bodies of water (mostly oceans and rivers) as a common theme, as mentioned by Delany in The Polymath. Though not a theme, coffee, more than any other beverage, is mentioned significantly and often in many of Delany\'s fictions.','2014-11-18 05:38:47',0,'* * *'),(55,34,'His reputation as a writer of courage and vision was established with the publication of The Martian Chronicles in 1950, which describes the first attempts of Earth people to conquer and colonize Mars, and the unintended consequences. Next came The Illustrated Man and then, in 1953, Fahrenheit 451, which many consider to be Bradbury\'s masterpiece, a scathing indictment of censorship set in a future world where the written word is forbidden. In an attempt to salvage their history and culture, a group of rebels memorize entire works of literature and philosophy as their books are burned by the totalitarian state. Other works include The October Country, Dandelion Wine, A Medicine for Melancholy, Something Wicked This Way Comes, I Sing the Body Electric!, Quicker Than the Eye, and Driving Blind. In all, Bradbury has published more than thirty books, close to 600 short stories, and numerous poems, essays, and plays. His short stories have appeared in more than 1,000 school curriculum \"recommended reading\" anthologies. ','2014-11-18 05:41:06',1,'Ray Bradbury, American novelist, short story writer, essayist, playwright, screenwriter and poet.'),(56,34,'Ray Bradbury\'s work has been included in four Best American Short Story collections. He has been awarded the O. Henry Memorial Award, the Benjamin Franklin Award, the World Fantasy Award for Lifetime Achievement, the Grand Master Award from the Science Fiction Writers of America, the PEN Center USA West Lifetime Achievement Award, among others. In November 2000, the National Book Foundation Medal for Distinguished Contribution to American Letters was conferred upon Mr. Bradbury at the 2000 National Book Awards Ceremony in New York City. ','2014-11-18 05:41:36',0,'* * *'),(57,34,'Clifford Donald Simak (* August 3, 1904 in Milville, Wisconsin, USA / â  April 25, 1988 in Minneapolis, Minnesota, USA) was a journalist and a science fiction writer. Simak was considered as one of the âGrandmastersâ of science fiction and he was honoured several times with awards for his contribution to science fiction literature.\r\n\r\nClifford D. Simak wrote continuously science fiction and fantasy for over 55 years (only few other writers worked as long as he did). He never was such a prolific writer like Isak Asimov or Robert Silverberg. Anyhow he managed to publish in these 55 years 28 novels and more than 120 short stories in the genres science fiction and fantasy â and that avocational until his retirement in 1976. He earned his living as a reporter and editor of big newspapers in the American middle west.\r\n\r\nThere was a time when Simak was considered as one of the most valued SF-writers and there was hardly any standard literature on the history of science fiction which has not dedicate him a separate paragraph or even an own chapter even though he was never in fashion. He stood mostly in the shadow of his more famous colleagues.','2014-11-18 05:43:33',1,'Clifford D. Simak');
/*!40000 ALTER TABLE `post` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2014-11-18 15:39:50
